### PR TITLE
Create 360giving.md

### PR DESCRIPTION
**Pull request by ekoner**
Based on the Open Contracting entry.
Disclosure: I'm part of the support team for this standard.

### CODE REVIEW

**Comment by rcheetham** [comment]
@ekoner Thanks for the contribution.  Thus far, we have limited this standards document to those standards specific to government operations. Is the 360Giving standard being used by local governments in the UK?

**Comment by ekoner** [comment]
@rcheetham Trafford Council have published to the standard (local government) and Cabinet Office (central government). Other councils have committed and are preparing their data.

**Comment by rcheetham** [comment]
@ekoner Sounds good. Could you please edit your PR to indicate that while it was developed for philanthropy giving, it is in active use by local and national government with several local councils committed to publishing grant data in this format?

**Comment by ekoner** [comment]
@rcheetham done! Thanks for the feedback.

**Pull request merged**
